name: Lint Pull Request
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "\\[(ID-[0-9]+)\\]" # Regex the title should match
          helpMessage: "Please provide a title for your PR."
